name: "Run Python script in pyction"
description: "Run a given Python script inside the pyction container using uv"

inputs:
  script:
    description: "Shell script to run inside the container"
    required: true

runs:
  using: "docker"
  image: "docker://ghcr.io/civicactions/pyction:latest"
  args:
    - bash
    - -c
    - |
      cd /github/workspace
      uv sync
      ${{ inputs.script }}
