name: security
on: [push, pull_request]

jobs:
  hardening:
    uses: huntridge-labs/hardening-workflows/.github/workflows/reusable-security-hardening.yml@main
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    with:
      scanners: codeql,opengrep,bandit,gitleaks
      python_version: '3.12'
      post_pr_comment: true
      codeql_languages: 'python'#
