# .github/workflows/security.yml
name: security

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 4 * * *' # nightly @ 04:00 UTC
  workflow_dispatch:

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 1️⃣ Linting
  linting:
    name: Lint & Format Check
    uses: huntridge-labs/hardening-workflows/.github/workflows/linting.yml@main
    permissions:
      contents: read
      pull-requests: write
      checks: write

  # 2️⃣ Core Security Scanners (SAST + IaC + SBOM by path)
  security:
    name: Security Hardening
    needs: linting
    if: always()
    uses: huntridge-labs/hardening-workflows/.github/workflows/reusable-security-hardening.yml@2.4.0
    permissions:
      contents: read
      security-events: write
      pull-requests: write

    with:
      scanners: codeql,opengrep,bandit,gitleaks,trivy-iac,checkov,sbom
      python_version: '3.12'
      post_pr_comment: true
      codeql_languages: 'python'
      iac_path: 'infrastructure'
      enable_code_security: true

  # 3️⃣ Container Image Build
  build_image:
    name: Build & Push Container
    needs: linting
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' || github.base_ref == 'main' ||
      github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
    outputs:
      image_ref: ${{ steps.meta.outputs.image_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        id: build
        run: |
          IMAGE="ghcr.io/${{ github.repository }}/pyction:${{ github.sha }}"
          docker build -t "$IMAGE" .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push image
        run: docker push "$IMAGE"

      - name: Set output
        id: meta
        run: echo "image_ref=$IMAGE" >> "$GITHUB_OUTPUT"

  # 4️⃣ Trivy Container Scan
  trivy_container:
    name: Trivy Container Scan
    needs: build_image
    uses: huntridge-labs/hardening-workflows/.github/workflows/scanner-trivy-container.yml@main
    permissions:
      contents: read
      security-events: write
    with:
      image_ref: ${{ needs.build_image.outputs.image_ref }}
      enable_code_security: true

  # 5️⃣ Grype Vulnerability Scan
  grype:
    name: Grype Vulnerability Scan
    needs: build_image
    uses: huntridge-labs/hardening-workflows/.github/workflows/scanner-grype.yml@main
    permissions:
      contents: read
    with:
      image_ref: ${{ needs.build_image.outputs.image_ref }}

  # 6️⃣ Syft SBOM (image)
  sbom_image:
    name: Syft SBOM (Container)
    needs: build_image
    uses: huntridge-labs/hardening-workflows/.github/workflows/scanner-syft.yml@main
    permissions:
      contents: read
    with:
      scan-image: ${{ needs.build_image.outputs.image_ref }}
