name: security
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  hardening:
    name: Security Hardening
    uses: huntridge-labs/hardening-workflows/.github/workflows/reusable-security-hardening.yml@main
    with:
      scanners: all
      python_version: '3.13# .github/workflows/security.yml'
      post_pr_comment: true
