name: security
on: [push, pull_request, workflow_dispatch]

jobs:
  hardening:
    name: Security Hardening
    uses: huntridge-labs/hardening-workflows/.github/workflows/reusable-security-hardening.yml@main
    permissions:
      contents: read
      security-events: write
      actions: read
      pull-requests: write
      checks: write
      id-token: write
    with:
      scanners: all
      python_version: '3.12'
      post_pr_comment: true
      enable_code_security: true
